version: '3'
services:
  mysql-standalone:
    image: 'mysql:8.0'
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=train_list
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: docker-build-trainsv2:1.0-SNAPSHOT
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://127.0.0.1:3306/train_list?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false"
      SPRING_DATASOURCE_USERNAME: "mysql"
      SPRING_DATASOURCE_PASSWORD: "mysql"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone